module.exports = (DataTypes) => {
    return {
        id:{
            type:DataTypes.BIGINT,
            allowNull:false,
            autoIncrement:true,
            primaryKey:true,
        },
        itemName:{
            type:DataTypes.STRING(50),
            allowNull:false,
            unique:true,
        },
        itemQuantity:{
            type:DataTypes.INTEGER,
            allowNull:false,
        },
        itemBuyPrice:{
            type:DataTypes.FLOAT(9,7),
            allowNull:false,
        },
        itemSellPrice:{
            type:DataTypes.FLOAT(9,7),
            allowNull:false,
        },
        itemRemaining:{
            type:DataTypes.INTEGER,
            allowNull:false,
        },
        itemSold:{
            type:DataTypes.INTEGER,
            allowNull:false,
        },
        itemCatagory:{
            type:DataTypes.STRING(50),
            allowNull:false,
        }
    }
};
