version: '3.7'

services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    image: app
    container_name: app
    ports:
      - 8080:8000
    env_file:
      - ./.env
    links:
      - db
    depends_on:
      - db
    volumes:
      - './:/backend'
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - dbvolume:/var/lib/postgresql/data

    ports:
      - 8001:5432

volumes:
  dbvolume:  
